table 1_Measures
	lineageTag: fca0b643-062c-4cfe-911a-63a9e040b594

	measure Greeting = ```
			var daytime = Hour(NOW())
			RETURN 
			Switch(True(),daytime > 0 && daytime <11,"Good Morning", daytime > 11 && daytime <17,"Good Afternoon", "Good Evening")
			```
		displayFolder: Main Measure
		lineageTag: 55708abb-07c4-4a49-8ecc-08d24676e1e5

	measure user =
			var UsernameLength = SEARCH(".",USERPRINCIPALNAME())
			var FirstName = Left(USERPRINCIPALNAME(),UsernameLength-1)
			var formattedfirstname=UPPER(LEFT(FirstName,1))&Mid(FirstName,2,UsernameLength-1)
			RETURN formattedfirstname
		displayFolder: Main Measure
		lineageTag: 3b394850-ceab-40d2-941b-4166c8eba7fa

	measure 'User Greeting' = ```
			[Greeting]&" "&[User] 
			```
		displayFolder: Main Measure
		lineageTag: 11d08df9-b4da-4f5f-8088-2ad85cdcefe4

	measure 'Refresh Message' = FORMAT(MAX('1_Measures'[Refresh Time]),"hh:nn, dd mmmm yyyy","en-GB")
		displayFolder: Refresh
		lineageTag: 2c4ae4c3-8c8c-4884-9972-ad1c82365ad5

	measure 'Clear Filters' = "  Clear Filters"
		displayFolder: Utility
		lineageTag: 23bcc3e0-e985-40e5-9256-4eb3aa19de8b

	column 'Refresh Time'
		dataType: dateTime
		formatString: Long Date
		displayFolder: Refresh
		lineageTag: 2207def7-225f-415b-b6a1-218bc95789e5
		summarizeBy: none
		sourceColumn: Refresh Time

		annotation SummarizationSetBy = Automatic

	partition 1_Measures = m
		mode: import
		source =
				let
				    Source = DateTime.LocalNow(),
				    #"Converted to table" = #table(1, {{Source}}),
				    Renamed = Table.RenameColumns(#"Converted to table",{{"Column1", "Refresh Time"}}),
				    #"Changed Type" = Table.TransformColumnTypes(Renamed,{{"Refresh Time", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

