/// 1_Measures table contains a single Date Time column, "Refresh Time," which indicates when the data in the semantic model was last refreshed.
table 1_Measures
	lineageTag: fca0b643-062c-4cfe-911a-63a9e040b594

	/// Displays the most recent refresh time of the data model as a formatted string message.
	measure 'Refresh Message' = FORMAT(MAX('1_Measures'[Refresh Time]),"hh:nn, dd mmmm yyyy","en-GB")
		displayFolder: Refresh
		lineageTag: 2c4ae4c3-8c8c-4884-9972-ad1c82365ad5

		changedProperty = IsHidden

	/// A static string value for Clear Filters.
	measure 'Clear Filters' = "  Clear Filters"
		displayFolder: Utility
		lineageTag: 23bcc3e0-e985-40e5-9256-4eb3aa19de8b

		changedProperty = IsHidden

	column 'Refresh Time'
		dataType: dateTime
		formatString: Long Date
		displayFolder: Refresh
		lineageTag: 2207def7-225f-415b-b6a1-218bc95789e5
		summarizeBy: none
		sourceColumn: Refresh Time

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 1_Measures = m
		mode: import
		source =
				let
				    Source = DateTime.LocalNow(),
				    #"Converted to table" = #table(1, {{Source}}),
				    Renamed = Table.RenameColumns(#"Converted to table",{{"Column1", "Refresh Time"}}),
				    #"Changed Type" = Table.TransformColumnTypes(Renamed,{{"Refresh Time", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

