/// 1_Measures table contains a single Date Time column, "Refresh Time," which indicates when the data in the semantic model was last refreshed.
table 1_Measures
	lineageTag: fca0b643-062c-4cfe-911a-63a9e040b594

	/// Displays the most recent refresh time of the data model as a formatted string message.
	measure 'Refresh Message' = FORMAT(MAX('1_Measures'[Refresh Time]),"hh:nn, dd mmmm yyyy","en-GB")
		displayFolder: Refresh
		lineageTag: 2c4ae4c3-8c8c-4884-9972-ad1c82365ad5

		changedProperty = IsHidden

	/// A static string value for Clear Filters.
	measure 'Clear Filters' = "  Clear Filters"
		displayFolder: Utility
		lineageTag: 23bcc3e0-e985-40e5-9256-4eb3aa19de8b

		changedProperty = IsHidden

	measure 'Count Rows' = ```
			
			ROW(
			    "JMS Table Row Count",
			    COUNTROWS('JMS Table')
			)
			
			```
		formatString: 0
		displayFolder: Doc. Measures
		lineageTag: 268acab6-f945-4605-a789-442b93309870

		changedProperty = IsHidden

	measure 'Target %' = 0.95
		formatString: 0%;-0%;0%
		displayFolder: Doc. Measures
		lineageTag: 53d564bd-3bf0-43bd-9068-832b4dc1d1d0

		changedProperty = IsHidden

	measure 'Review Day.' = DATEDIFF ( TODAY(), MIN('JMS Table'[ReviewDate]), DAY )
		formatString: 0%;-0%;0%
		displayFolder: Doc. Measures
		lineageTag: d46346c3-fa80-4e78-9d96-51db1bb55329

		changedProperty = IsHidden

	measure Docs = COUNTROWS('JMS Table')
		formatString: 0
		displayFolder: Doc. Measures
		lineageTag: 6ca8bae9-e728-4dcf-a550-46e09975f0fb

		changedProperty = IsHidden

	measure 'Docs within Date' = 1-((COUNTROWS(FILTER('JMS Table','JMS Table'[Expired and Compliant - Values]==1)))/COUNTROWS('JMS Table'))
		formatString: 0%;-0%;0%
		displayFolder: Doc. Measures
		lineageTag: dbdc41aa-1e23-4a4b-9d5a-5da9f2c49d34

		changedProperty = IsHidden

	measure 'Overdue Docs' =
			
			CALCULATE ( [Docs], FILTER( ALL('JMS Table'[ReviewDate]), [Review Day.] < 0 ) )
		formatString: 0
		displayFolder: Doc. Measures
		lineageTag: 3ce530eb-ff4a-47f0-98ff-8b023f9e0b0a

		changedProperty = IsHidden

	measure 'Review Count' = ```
			
			DISTINCTCOUNT ( 'JMS Table'[JMS ID] )
			
			```
		formatString: 0
		displayFolder: Doc. Measures
		lineageTag: 92dbfbcf-1966-4e58-b940-12da9e7420fb

	measure Items = ```
			
			    COUNTROWS('JMS Table')
			```
		formatString: 0
		displayFolder: Doc. Measures
		lineageTag: 731d175b-f294-49e9-8f84-52ec61470b0a

	column 'Refresh Time'
		dataType: dateTime
		formatString: Long Date
		displayFolder: Refresh
		lineageTag: 2207def7-225f-415b-b6a1-218bc95789e5
		summarizeBy: none
		sourceColumn: Refresh Time

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 1_Measures = m
		mode: import
		source =
				let
				    Source = DateTime.LocalNow(),
				    #"Converted to table" = #table(1, {{Source}}),
				    Renamed = Table.RenameColumns(#"Converted to table",{{"Column1", "Refresh Time"}}),
				    #"Changed Type" = Table.TransformColumnTypes(Renamed,{{"Refresh Time", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

