table 'EXAMPLE - Place Table'
	lineageTag: 916134b5-9d21-4390-bd27-256484ffb09a

	column statuscodename
		dataType: string
		lineageTag: c3f7f410-d8fc-4d2e-95c3-395739748696
		summarizeBy: none
		sourceColumn: statuscodename

		annotation SummarizationSetBy = Automatic

	column Code
		dataType: string
		lineageTag: 0b05a870-d807-420d-896a-c7de02370f2d
		summarizeBy: none
		sourceColumn: kbsint_code

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 9234ec14-92d4-4719-afe7-49165ecdda71
		summarizeBy: none
		sourceColumn: kbsint_name

		annotation SummarizationSetBy = Automatic

	column 'Site Code'
		dataType: string
		lineageTag: 5664db7e-cb35-4401-93e0-4433fbe41599
		summarizeBy: none
		sourceColumn: kbsint_sitecodename

		annotation SummarizationSetBy = Automatic

	column 'Place Status'
		dataType: string
		lineageTag: bd425e69-f166-4eee-8d2e-7782c6bc7c9e
		summarizeBy: none
		sourceColumn: crd9c_placestatusname

		annotation SummarizationSetBy = Automatic

	column 'Code & Name' = 'EXAMPLE - Place Table'[Code] & " - " & 'EXAMPLE - Place Table'[Name]
		displayFolder: _Calculated Columns
		lineageTag: d35eb142-aa09-4389-bee4-c5cbd99606f6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'EXAMPLE - Place Table' = m
		mode: import
		source =
				let
				    Source = CommonDataService.Database("keystone.crm11.dynamics.com"),
				    dbo_kbsint_place = Source{[Schema="dbo",Item="kbsint_place"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_kbsint_place,{"statuscodename", "kbsint_code", "kbsint_name", "kbsint_sitecodename", "crd9c_placestatusname"})
				in
				    #"Removed Other Columns"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

