table 'EXAMPLE - Projects'
	lineageTag: 318022db-1348-4fd8-aea4-d908f6721a13

	column 'Project ID'
		dataType: string
		lineageTag: 74616f9c-3dce-4b4a-8f9e-9fd061096513
		summarizeBy: none
		sourceColumn: Project ID

		annotation SummarizationSetBy = Automatic

	column 'Project Code'
		dataType: string
		lineageTag: 9aca2950-72b9-4de2-8c51-b16f9e933758
		summarizeBy: none
		sourceColumn: Project Code

		annotation SummarizationSetBy = Automatic

	column 'Project Name'
		dataType: string
		lineageTag: 926d2582-4cc4-455a-af75-fc1e149fda54
		summarizeBy: none
		sourceColumn: Project Name

		annotation SummarizationSetBy = Automatic

	column Programme
		dataType: string
		lineageTag: 63e2ab9b-30f4-4ad9-ba1a-06d2f175474c
		summarizeBy: none
		sourceColumn: Programme

		annotation SummarizationSetBy = Automatic

	column Discipline
		dataType: string
		lineageTag: ed35d5f4-1ad8-4e9e-85db-cb41e686deaa
		summarizeBy: none
		sourceColumn: Discipline

		annotation SummarizationSetBy = Automatic

	column 'Project Manager'
		dataType: string
		lineageTag: d7c3fb63-be60-4260-a356-c3934ed1aa73
		summarizeBy: none
		sourceColumn: Project Manager

		annotation SummarizationSetBy = Automatic

	column 'Design Lead'
		dataType: string
		lineageTag: a13a06dc-660a-4bbb-9f24-808c3cae48e4
		summarizeBy: none
		sourceColumn: Design Lead

		annotation SummarizationSetBy = Automatic

	column 'Programme Lead'
		dataType: string
		lineageTag: ea6989bd-c578-4510-b378-7b7711a387d9
		summarizeBy: none
		sourceColumn: Programme Lead

		annotation SummarizationSetBy = Automatic

	column 'Supply Chain Lead'
		dataType: string
		lineageTag: bed234db-bdf0-4081-8700-10e64058ff3a
		summarizeBy: none
		sourceColumn: Supply Chain Lead

		annotation SummarizationSetBy = Automatic

	column 'MOD Lead'
		dataType: string
		lineageTag: 3fe6a623-5923-4bb1-9ede-cf774023c697
		summarizeBy: none
		sourceColumn: MOD Lead

		annotation SummarizationSetBy = Automatic

	column TAF
		dataType: string
		lineageTag: 327c1713-c3be-4ade-92bf-fbbe495ea93f
		summarizeBy: none
		sourceColumn: TAF

		annotation SummarizationSetBy = Automatic

	column 'Business Case Item'
		dataType: string
		lineageTag: 93851b8b-8662-4cd8-b840-b957a8f20f23
		summarizeBy: none
		sourceColumn: Business Case Item

		annotation SummarizationSetBy = Automatic

	column 'Business Case'
		dataType: string
		lineageTag: 7b177464-86a3-4015-a685-68bd48e5f16f
		summarizeBy: none
		sourceColumn: Business Case

		annotation SummarizationSetBy = Automatic

	column 'Latest Note'
		dataType: string
		lineageTag: ed444a10-54fa-452d-a4b3-8797630dc407
		summarizeBy: none
		sourceColumn: Latest Note

		annotation SummarizationSetBy = Automatic

	column 'Latest Note Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6bdc8a0b-8cb5-480a-95bb-af6e78d8136c
		summarizeBy: none
		sourceColumn: Latest Note Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Completion
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0651e19d-5ba2-4401-9d11-c0edc38198f0
		summarizeBy: sum
		sourceColumn: Completion

		annotation SummarizationSetBy = Automatic

	column 'Risk Score'
		dataType: int64
		formatString: 0
		lineageTag: af08057e-cb4b-480e-8cfe-34be385d9293
		summarizeBy: sum
		sourceColumn: Risk Score

		annotation SummarizationSetBy = Automatic

	column 'Risk Rating'
		dataType: string
		lineageTag: e3aa567e-b709-4aaf-b14f-3b898d0f4eb1
		summarizeBy: none
		sourceColumn: Risk Rating
		sortByColumn: 'Risk Score'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Risk Comments'
		dataType: string
		lineageTag: da418841-7072-45c8-b907-3baac2483ab3
		summarizeBy: none
		sourceColumn: Risk Comments

		annotation SummarizationSetBy = Automatic

	column 'Current Gateway Stage'
		dataType: string
		lineageTag: 2e90979b-2871-4d7c-8d11-9434adeaa5a2
		summarizeBy: none
		sourceColumn: Current Gateway Stage

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: f12d8ea9-6418-42c1-a69d-4d48fd9ad47b
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'On Hold Reason'
		dataType: string
		lineageTag: a78b6f3d-ddd2-488b-96c3-8bee680b93d8
		summarizeBy: none
		sourceColumn: On Hold Reason

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		lineageTag: 774b9f8b-c590-433e-a478-e070bdd95f3d
		summarizeBy: none
		sourceColumn: Priority

		annotation SummarizationSetBy = Automatic

	column 'Project Status'
		dataType: string
		lineageTag: 4590e3b3-1e55-4007-91e8-42dac7f33f68
		summarizeBy: none
		sourceColumn: Project Status

		annotation SummarizationSetBy = Automatic

	column 'Schedule Health'
		dataType: string
		lineageTag: e6615be9-bd7c-48b2-9d69-4872c2ebe4f8
		summarizeBy: none
		sourceColumn: Schedule Health

		annotation SummarizationSetBy = Automatic

	column 'Issue Health'
		dataType: string
		lineageTag: 855bbf55-6e49-4a77-9aa1-6c92cf9dad30
		summarizeBy: none
		sourceColumn: Issue Health

		annotation SummarizationSetBy = Automatic

	column 'Effort Health'
		dataType: string
		lineageTag: 5c0fc267-a966-4520-acf8-aa7e5034b667
		summarizeBy: none
		sourceColumn: Effort Health

		annotation SummarizationSetBy = Automatic

	column 'Financial Health'
		dataType: string
		lineageTag: 122a697b-c5b4-4f62-bcdd-d4e54a119046
		summarizeBy: none
		sourceColumn: Financial Health

		annotation SummarizationSetBy = Automatic

	column 'Overall Health'
		dataType: string
		lineageTag: eb696870-0dae-4f81-b0c7-f483a7cd7f94
		summarizeBy: none
		sourceColumn: Overall Health

		annotation SummarizationSetBy = Automatic

	column Progress
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 1bcc819a-ef13-4166-8d6e-2c9a99840d4c
		summarizeBy: sum
		sourceColumn: Progress

		annotation SummarizationSetBy = Automatic

	column Budget
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: d2ffdd4b-995b-4687-bb32-58c9373523ef
		summarizeBy: sum
		sourceColumn: Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'Remaining Budget'
		dataType: double
		lineageTag: b7d4f147-cadb-4dd8-9776-d2e8a4ce5e46
		summarizeBy: sum
		sourceColumn: Remaining Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '% Remaining Budget'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e3e46f07-2a34-4f84-b277-a97546510d30
		summarizeBy: sum
		sourceColumn: % Remaining Budget

		annotation SummarizationSetBy = Automatic

	column 'Variance from Budget'
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 41f94828-b13f-4eee-b286-021e0b8ad452
		summarizeBy: sum
		sourceColumn: Variance from Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'Actual Spend'
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 523af248-483c-434c-b273-a0c8f730ac7a
		summarizeBy: sum
		sourceColumn: Actual Spend

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'Base Budget'
		dataType: double
		formatString: "£"#,0.00;-"£"#,0.00;"£"#,0.00
		lineageTag: 0190616c-2b6f-4785-a403-0c83497fb2b2
		summarizeBy: sum
		sourceColumn: Base Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'Remaining Base Budget'
		dataType: double
		lineageTag: 7ce29d0e-045e-4eae-98a9-503a0952b7b7
		summarizeBy: sum
		sourceColumn: Remaining Base Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '% Remaining Base Budget'
		dataType: double
		lineageTag: bc24310e-ffd2-435d-a640-1d2b54bf552d
		summarizeBy: sum
		sourceColumn: % Remaining Base Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Variance from Base Budget'
		dataType: double
		lineageTag: 6fdef70c-e2ff-410c-9cc4-6b1d3152b2a8
		summarizeBy: sum
		sourceColumn: Variance from Base Budget

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column kbsint_deliverygatewayname
		dataType: string
		lineageTag: 6282f436-1f85-4af7-8208-7fcef12aa131
		summarizeBy: none
		sourceColumn: kbsint_deliverygatewayname

		annotation SummarizationSetBy = Automatic

	column 'Earliest Task Start'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c1b1254a-e7c8-4489-9a58-43fab1e8e5a4
		summarizeBy: none
		sourceColumn: Earliest Task Start

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Scheduled Start Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 08d9297c-a262-494a-8a44-e1ec8a7e9030
		summarizeBy: none
		sourceColumn: Scheduled Start Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Baseline 1 Finish Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 542e5ae3-bf24-479a-8f73-df211989fa42
		summarizeBy: none
		sourceColumn: Baseline 1 Finish Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Baseline 2 Finish Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b4913b98-3361-4f0d-af04-c618ad777703
		summarizeBy: none
		sourceColumn: Baseline 2 Finish Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Baseline 3 Finish Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1af0a02c-4609-449a-9cb8-0d1197c2affc
		summarizeBy: none
		sourceColumn: Baseline 3 Finish Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Actual Finish Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c74223ae-bf5b-484b-8103-6bb795b4a86b
		summarizeBy: none
		sourceColumn: Actual Finish Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'BS2 Duration'
		dataType: int64
		formatString: 0
		lineageTag: 253d73d2-09a5-494d-9683-dd77b2c11385
		summarizeBy: sum
		sourceColumn: BS2 Duration

		annotation SummarizationSetBy = Automatic

	column 'BS3 Duration'
		dataType: int64
		formatString: 0
		lineageTag: e2bb5d23-978b-4656-8f74-a87312bcaaec
		summarizeBy: sum
		sourceColumn: BS3 Duration

		annotation SummarizationSetBy = Automatic

	column 'Actual Duration'
		dataType: int64
		formatString: 0
		lineageTag: 0535a323-034d-4fce-b800-10db6345a9a5
		summarizeBy: sum
		sourceColumn: Actual Duration

		annotation SummarizationSetBy = Automatic

	column 'Current Duration'
		dataType: int64
		formatString: 0
		lineageTag: 711d270a-74ea-4484-b8a6-032c469ab0cd
		summarizeBy: sum
		sourceColumn: Current Duration

		annotation SummarizationSetBy = Automatic

	column 'Time Remaining'
		dataType: int64
		formatString: 0
		lineageTag: efe144d0-2313-4e01-98d4-c5a2ddda7b28
		summarizeBy: sum
		sourceColumn: Time Remaining

		annotation SummarizationSetBy = Automatic

	column 'Keystone Link'
		dataType: string
		lineageTag: a4d7aabd-12e7-427d-9718-65dd86c28e51
		summarizeBy: none
		sourceColumn: Keystone Link

		annotation SummarizationSetBy = Automatic

	column _CodeAndProject = 'EXAMPLE - Projects'[Project Code]&" - "&'EXAMPLE - Projects'[Project Name]
		displayFolder: _Calculated Columns
		lineageTag: d23918d3-dc4f-46ee-b493-2164cf4bd0c2
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column _TimeRemainingFlag =
			SWITCH(
			    TRUE(),
			    'EXAMPLE - Projects'[Time Remaining] < 0, 1,
			    'EXAMPLE - Projects'[Time Remaining] >= 0, 0,
			    -10000000000000)
		formatString: 0
		displayFolder: _Calculated Columns
		lineageTag: f437f45b-677f-496b-9e62-e6d4428a297e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column _MissingDesignLead =
			SWITCH(
			    'EXAMPLE - Projects'[Design Lead],
			    BLANK(), 1,
			    0
			)
		formatString: 0
		displayFolder: _Calculated Columns
		lineageTag: bb80967f-42ca-42b2-85d5-bdf1918dbf78
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column _SanitisedRisk =
			SWITCH(
			    'EXAMPLE - Projects'[Risk Score],
			    0, BLANK(),
			    BLANK(), BLANK(),
			    'EXAMPLE - Projects'[Risk Score]
			)
		formatString: 0
		displayFolder: _Calculated Columns
		lineageTag: 74084dd4-2d6e-4ec3-837f-bcf8d5a928ee
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Place Code'
		dataType: string
		lineageTag: 7f92cf48-b2ef-4b67-bd17-df1492c52b3a
		summarizeBy: none
		sourceColumn: Place Code

		annotation SummarizationSetBy = Automatic

	partition 'EXAMPLE - Projects' = m
		mode: import
		source =
				let
				    Source = Sql.Database("naenjfte7yyutocra75vmno4rq-2r3kgxrfu7kethsqhz5vns6emy.datawarehouse.fabric.microsoft.com", "Programme_Delivery"),
				    #"dbo_Project Current Status" = Source{[Schema="dbo",Item="Project Current Status"]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(#"dbo_Project Current Status",null,"0 - left empty",Replacer.ReplaceValue,{"Discipline"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",null,"0 - left empty",Replacer.ReplaceValue,{"Risk Rating"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1",null,0,Replacer.ReplaceValue,{"Progress"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","01. PRF and Definition","01. Definition and PRF",Replacer.ReplaceText,{"Current Gateway Stage"}),
				    #"Merged Queries" = Table.NestedJoin(#"Replaced Value3", {"Project Code"}, #"EXAMPLE - msdyn_project", {"crd9c_projectidcode"}, "msdyn_project", JoinKind.LeftOuter),
				    #"Expanded msdyn_project" = Table.ExpandTableColumn(#"Merged Queries", "msdyn_project", {"crd9c_placecode"}, {"crd9c_placecode"}),
				    #"Removed Duplicates" = Table.Distinct(#"Expanded msdyn_project", {"Project Code"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Duplicates",{{"crd9c_placecode", "Place Code"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

