/// JMS Table stores document details such as title, owner, review dates, compliance status, priority, and related comments, supporting document tracking and review management. This table is designed to support document management processes by capturing key metadata and review-related details for each document entry.
table 'JMS Table'
	lineageTag: 2784e14b-688d-4cd3-bb04-27254fe08744

	column Id
		dataType: string
		lineageTag: 5b150f5f-30fa-4f31-9d1e-40dfb539ca49
		summarizeBy: none
		sourceColumn: Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Document Link'
		dataType: string
		lineageTag: 6e808836-5ff6-4aba-9cbd-f0a22a0a9da1
		summarizeBy: none
		sourceColumn: Document Link

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		lineageTag: 432b9a85-9ba3-42fb-b378-fa1d529d0f7a
		summarizeBy: none
		sourceColumn: Title

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DocumentOwnerId
		dataType: string
		lineageTag: 8a91ddd3-7bc3-4d6f-a701-a8cd3d68ef4f
		summarizeBy: none
		sourceColumn: DocumentOwnerId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ReviewDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: e103190d-e749-4beb-9758-aef2e8bd688d
		summarizeBy: none
		sourceColumn: ReviewDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column JMSIDLookupId
		dataType: string
		lineageTag: 5913a0ae-bc05-445f-bb1e-b55bdab5bb41
		summarizeBy: none
		sourceColumn: JMSIDLookupId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ParentIDLookupId
		dataType: string
		lineageTag: 73e50468-8401-4632-b417-54641df0432c
		summarizeBy: none
		sourceColumn: ParentIDLookupId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Quality Team Comments'
		dataType: string
		lineageTag: f25c6ce1-c2ea-41c3-aa8e-b5496ba24950
		summarizeBy: none
		sourceColumn: Quality Team Comments

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Process AuthorityId'
		dataType: string
		lineageTag: f1500ff3-aced-4de0-9239-817bffd61b1e
		summarizeBy: none
		sourceColumn: Process AuthorityId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BusinessAreaL1
		dataType: string
		lineageTag: bc30cc8c-e9cf-45e9-9807-a334eb0eb611
		summarizeBy: none
		sourceColumn: BusinessAreaL1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ContinualImprovementRequired
		dataType: string
		lineageTag: 8ced798b-5a9d-43a8-9628-3ece04bd6e54
		summarizeBy: none
		sourceColumn: ContinualImprovementRequired

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: string
		lineageTag: d201f1c9-9b2f-4cca-9e99-a7303a18fceb
		summarizeBy: none
		sourceColumn: Created

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AuthorId
		dataType: string
		lineageTag: c6afb17b-d34c-49f2-81d1-1d98af3ba4c2
		summarizeBy: none
		sourceColumn: AuthorId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Modified
		dataType: string
		lineageTag: 879e14e4-70dc-4190-bdb6-ff87db74a0a4
		summarizeBy: none
		sourceColumn: Modified

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Content Type'
		dataType: string
		lineageTag: 8a0d95b1-dfa5-4f9d-acd0-59736cfa8262
		summarizeBy: none
		sourceColumn: Content Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'JMS ID'
		dataType: int64
		formatString: 0
		lineageTag: 74d956c8-e19e-46a5-945d-7434a61a2771
		summarizeBy: sum
		sourceColumn: JMS ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Document Owner'
		dataType: string
		lineageTag: 14d430e1-0492-447e-b9fa-a7c8392cb203
		summarizeBy: none
		sourceColumn: Document Owner

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Process Authority'
		dataType: string
		lineageTag: a8b71259-39a0-4303-8f65-8b76b75f9400
		summarizeBy: none
		sourceColumn: Process Authority

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Review Days'
		dataType: string
		lineageTag: 7f9facec-67c2-4e42-b737-ee2ba2271686
		summarizeBy: none
		sourceColumn: Review Days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Review Priority'
		dataType: string
		lineageTag: e6d3e907-1fec-4461-bc72-05445e1dba0d
		summarizeBy: none
		sourceColumn: Review Priority
		sortByColumn: 'Priority.1'

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Compliant and Expired'
		dataType: string
		lineageTag: 85214c79-e55f-4c53-b759-da4931c0a934
		summarizeBy: none
		sourceColumn: Compliant and Expired

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Expired and Compliant - Values'
		dataType: int64
		formatString: 0
		lineageTag: 8161525d-7f71-4ad1-915d-4c5709cda8fb
		summarizeBy: sum
		sourceColumn: Expired and Compliant - Values

		changedProperty = IsHidden

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Owner Email'
		dataType: string
		lineageTag: b6177509-b6e1-4e83-a20a-2b408d9bd6a0
		summarizeBy: none
		sourceColumn: Owner Email

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Priority.1'
		dataType: string
		lineageTag: 7e49c46f-f4c7-4118-bf69-cc05c06895be
		summarizeBy: none
		sourceColumn: Priority.1

		annotation SummarizationSetBy = Automatic

	partition 'JMS Table' = m
		mode: import
		source =
				let
				    Source = SharePoint.Tables("https://kbsmaritime.sharepoint.com/sites/JointManagementSystem", [ApiVersion = 15]),
				    #"7a204d33-f1a5-4660-9105-822ef3cfee94" = Source{[Id="7a204d33-f1a5-4660-9105-822ef3cfee94"]}[Items],
				    #"Expand table to extract Content Type" = Table.ExpandRecordColumn(#"7a204d33-f1a5-4660-9105-822ef3cfee94", "ContentType", {"Name"}, {"ContentType.Name"}),
				    #"Removed the Prefix (JMS)" = Table.ReplaceValue(#"Expand table to extract Content Type","JMS","",Replacer.ReplaceText,{"ContentType.Name"}),
				    #"Renamed Col. to Content Type" = Table.RenameColumns(#"Removed the Prefix (JMS)",{{"ContentType.Name", "Content Type"}}),
				    #"Expanded FieldValuesAsHtml" = Table.ExpandRecordColumn(#"Renamed Col. to Content Type", "FieldValuesAsHtml", {"FileLeafRef", "Title"}, {"FieldValuesAsHtml.FileLeafRef", "FieldValuesAsHtml.Title"}),
				    #"Expanded DocumentOwner" = Table.ExpandRecordColumn(#"Expanded FieldValuesAsHtml", "DocumentOwner", {"Title"}, {"DocumentOwner.Title"}),
				    #"Renamed Column to Doc. Owner" = Table.RenameColumns(#"Expanded DocumentOwner",{{"DocumentOwner.Title", "Document Owner"}}),
				    #"Expand to extract Process Authority" = Table.ExpandRecordColumn(#"Renamed Column to Doc. Owner", "Process Authority", {"Title"}, {"Process Authority.Title"}),
				    #"Renamed to Process Authority" = Table.RenameColumns(#"Expand to extract Process Authority",{{"Process Authority.Title", "Process Authority"}}),
				    #"Expanded to Extract Review Date" = Table.ExpandRecordColumn(#"Renamed to Process Authority", "FieldValuesAsText", {"ReviewDate"}, {"FieldValuesAsText.ReviewDate"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded to Extract Review Date",{{"ServerRedirectedEmbedUrl", "Document Link"}}),
				    #"Changed to DateType" = Table.TransformColumnTypes(#"Renamed Columns",{{"ReviewDate", type date}}),
				    #"Filtered out nulls" = Table.SelectRows(#"Changed to DateType", each ([ReviewDate] <> null)),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Filtered out nulls", "FieldValuesAsHtml.FileLeafRef", Splitter.SplitTextByEachDelimiter({"-"}, QuoteStyle.Csv, false), {"FieldValuesAsHtml.FileLeafRef.1", "FieldValuesAsHtml.FileLeafRef.2"}),
				    #"Renamed Col. to JMS ID" = Table.RenameColumns(#"Split Column by Delimiter",{{"FieldValuesAsHtml.FileLeafRef.1", "JMS ID"}}),
				    #"Split Column by Delimiter1" = Table.SplitColumn(#"Renamed Col. to JMS ID", "FieldValuesAsHtml.FileLeafRef.2", Splitter.SplitTextByEachDelimiter({"."}, QuoteStyle.Csv, true), {"FieldValuesAsHtml.FileLeafRef.2.1", "FieldValuesAsHtml.FileLeafRef.2.2"}),
				    #"Changed Data Type" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"JMS ID", Int64.Type}, {"FieldValuesAsHtml.FileLeafRef.2.1", type text}, {"FieldValuesAsHtml.FileLeafRef.2.2", type text}}),
				    #"Changed column name to ID" = Table.RenameColumns(#"Changed Data Type",{{"ID", "ID.1"}}),
				    #"Removed Suffix" = Table.ReplaceValue(#"Changed column name to ID","(KBS PC)","",Replacer.ReplaceText,{"Document Owner"}),
				    #"Days to Review" = Table.AddColumn(#"Removed Suffix", "Review Days", each Duration.Days([ReviewDate] - Date.From(DateTime.LocalNow()))),
				    #"Defined Review Priority" = Table.AddColumn(#"Days to Review", "Review Priority", each if  [Review Days]<= 0 then "Overdue"
				  else if [Review Days] >= 1 and [Review Days] < 30 then "01-30 Days"
				  else if [Review Days] >= 30 and [Review Days] < 60 then "31-60 Days"
				  else if [Review Days] >= 60 and [Review Days]< 90 then "61-90 Days"
				  else if [Review Days] < 365 then " = 1Year"
				  else "> 1Year"),
				    #"Compliant and Expired Status (Defined)" = Table.AddColumn(#"Defined Review Priority", "Compliant and Expired", each if [Review Priority] = "Overdue" then "Overdue" else "Complaint"),
				    #"Expired and Compliant - Outcome" = Table.AddColumn(#"Compliant and Expired Status (Defined)", "Expired and Compliant - Values", each if [Compliant and Expired] = "Overdue" then 1 else 2),
				    #"Replaced 'Null' with No Comment" = Table.ReplaceValue(#"Expired and Compliant - Outcome",null,"No Comment",Replacer.ReplaceValue,{"JMSReadyTBCComments"}),
				    #"Renamed to Quality Team Comments" = Table.RenameColumns(#"Replaced 'Null' with No Comment",{{"JMSReadyTBCComments", "Quality Team Comments"}}),
				    #"Added Owner Email Address" = Table.AddColumn(#"Renamed to Quality Team Comments", "Owner Email", each Text.Lower(Text.Replace([Document Owner], " ", ".")) & "@kbsMaritime.com"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Owner Email Address",{{"ContinualImprovementRequired", type text}}),
				    #"Replaced true with Yes" = Table.ReplaceValue(#"Changed Type","true","Yes",Replacer.ReplaceText,{"ContinualImprovementRequired"}),
				    #"Excluded Columns not Needed" = Table.RemoveColumns(#"Replaced true with Yes",{"FileSystemObjectType", "ServerRedirectedEmbedUri", "ContentTypeId", "ComplianceAssetId", "DocumentOwnerStringId", "MethodStatementServiceDeliveryPlan", "OData__Copyright", "URL", "Additional AuthorisersId", "Additional AuthorisersStringId", "External Ref. Type", "Mgt. Plan Type", "Standard Type", "Strategy Type", "Eng. Auth. Req'd?", "SHE Auth. Req'd?", "SharedWithUsersId", "SharedWithDetails", "IM Auth. Req'd?", "OData__ColorTag", "VControlTableAdded", "Mgt. System", "ReviewPeriod", "Process AuthorityStringId", "OData__ip_UnifiedCompliancePolicyProperties", "Document MS IDId", "ID.1", "EditorId", "OData__CopySource", "CheckoutUserId", "OData__UIVersionString", "GUID", "FirstUniqueAncestorSecurableObject", "RoleAssignments", "AttachmentFiles", "GetDlpPolicyTip", "FieldValuesAsHtml.FileLeafRef.2.1", "FieldValuesAsHtml.FileLeafRef.2.2", "FieldValuesAsHtml.Title", "FieldValuesAsText.ReviewDate", "FieldValuesForEdit", "File", "Folder", "LikedByInformation", "ParentList", "Properties", "Versions", "Additional Authorisers", "TaxCatchAll", "SharedWithUsers", "JMSIDLookup", "ParentIDLookup", "Document MS ID", "Author", "CheckoutUser", "Editor"}),
				    #"Merged Queries" = Table.NestedJoin(#"Excluded Columns not Needed", {"Review Priority"}, Priority, {"Review Priority"}, "Priority", JoinKind.LeftOuter),
				    #"Expanded Priority" = Table.ExpandTableColumn(#"Merged Queries", "Priority", {"Priority"}, {"Priority.1"}),
				    #"Removed Suffix (KBS PC)" = Table.ReplaceValue(#"Expanded Priority","(KBS PC)","",Replacer.ReplaceText,{"Process Authority"})
				in
				    #"Removed Suffix (KBS PC)"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

