/// JMS Table stores document details such as title, owner, review dates, compliance status, priority, and related comments, supporting document tracking and review management. This table is designed to support document management processes by capturing key metadata and review-related details for each document entry.
table 'JMS Table (2)'
	isHidden
	lineageTag: 2784e14b-688d-4cd3-bb04-27254fe08744

	column FileSystemObjectType
		dataType: string
		isHidden
		lineageTag: 67a62af9-6896-4a80-81b2-cfab911f6533
		summarizeBy: none
		sourceColumn: FileSystemObjectType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Id
		dataType: string
		isHidden
		lineageTag: 5b150f5f-30fa-4f31-9d1e-40dfb539ca49
		summarizeBy: none
		sourceColumn: Id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Document Link'
		dataType: string
		isHidden
		lineageTag: 22d66619-ee47-4b0d-a086-83db7855d532
		summarizeBy: none
		sourceColumn: Document Link

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ServerRedirectedEmbedUrl
		dataType: string
		isHidden
		lineageTag: 6e808836-5ff6-4aba-9cbd-f0a22a0a9da1
		summarizeBy: none
		sourceColumn: ServerRedirectedEmbedUrl

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ContentTypeId
		dataType: string
		isHidden
		lineageTag: 9fb6a59c-9927-4354-b512-f1f4af32cccf
		summarizeBy: none
		sourceColumn: ContentTypeId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ComplianceAssetId
		dataType: string
		isHidden
		lineageTag: cf2fac59-aff0-43d1-a845-88c58bee7d7e
		summarizeBy: none
		sourceColumn: ComplianceAssetId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		isHidden
		lineageTag: 432b9a85-9ba3-42fb-b378-fa1d529d0f7a
		summarizeBy: none
		sourceColumn: Title

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DocumentOwnerId
		dataType: string
		isHidden
		lineageTag: 8a91ddd3-7bc3-4d6f-a701-a8cd3d68ef4f
		summarizeBy: none
		sourceColumn: DocumentOwnerId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DocumentOwnerStringId
		dataType: string
		isHidden
		lineageTag: a7b64539-50d8-4352-b41f-4d4ca5d3d9bd
		summarizeBy: none
		sourceColumn: DocumentOwnerStringId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MethodStatementServiceDeliveryPlan
		dataType: string
		isHidden
		lineageTag: 1bad140d-a1aa-4ab3-b3dc-9124a6b237ea
		summarizeBy: none
		sourceColumn: MethodStatementServiceDeliveryPlan

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OData__Copyright
		dataType: string
		isHidden
		lineageTag: 20b1c55b-8920-43ef-ba1f-ec4315cf1007
		summarizeBy: none
		sourceColumn: OData__Copyright

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ReviewDate
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: e103190d-e749-4beb-9758-aef2e8bd688d
		summarizeBy: none
		sourceColumn: ReviewDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column URL
		dataType: string
		isHidden
		lineageTag: fb34f1c7-9cf7-4858-bef5-4ecafda94df6
		summarizeBy: none
		sourceColumn: URL

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Additional AuthorisersId'
		dataType: string
		isHidden
		lineageTag: 330ea2f4-8722-470a-a185-528a5d76a965
		summarizeBy: none
		sourceColumn: Additional AuthorisersId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Additional AuthorisersStringId'
		dataType: string
		isHidden
		lineageTag: ba39c64a-9f87-41e7-b7ef-a77ddb582ff8
		summarizeBy: none
		sourceColumn: Additional AuthorisersStringId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'External Ref. Type'
		dataType: string
		isHidden
		lineageTag: 2e50effb-e4df-4e1c-89de-de49b3ca2742
		summarizeBy: none
		sourceColumn: External Ref. Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Mgt. Plan Type'
		dataType: string
		isHidden
		lineageTag: 52357955-1cc7-4ec4-8665-c2503f3294f5
		summarizeBy: none
		sourceColumn: Mgt. Plan Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Standard Type'
		dataType: string
		isHidden
		lineageTag: bc42a2a4-7dd0-45c3-8f06-78c9896cead7
		summarizeBy: none
		sourceColumn: Standard Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Strategy Type'
		dataType: string
		isHidden
		lineageTag: 132c743c-2211-412c-9ea7-43bd9db7371c
		summarizeBy: none
		sourceColumn: Strategy Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Eng. Auth. Req''d?'
		dataType: string
		isHidden
		lineageTag: ea311d96-8a4a-4130-881e-cdc9c9f0bd7b
		summarizeBy: none
		sourceColumn: Eng. Auth. Req'd?

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'SHE Auth. Req''d?'
		dataType: string
		isHidden
		lineageTag: ac17049f-b66a-468e-829c-e61aa569a983
		summarizeBy: none
		sourceColumn: SHE Auth. Req'd?

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SharedWithUsersId
		dataType: string
		isHidden
		lineageTag: cae52305-5b4f-4fb6-ba19-876550e5cd5b
		summarizeBy: none
		sourceColumn: SharedWithUsersId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SharedWithDetails
		dataType: string
		isHidden
		lineageTag: bdb624a8-a5aa-420a-b9cb-e393be750dab
		summarizeBy: none
		sourceColumn: SharedWithDetails

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'IM Auth. Req''d?'
		dataType: string
		isHidden
		lineageTag: a2f7175e-6ac8-4a45-9532-2c5fee7bacb9
		summarizeBy: none
		sourceColumn: IM Auth. Req'd?

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column JMSIDLookupId
		dataType: string
		isHidden
		lineageTag: 5913a0ae-bc05-445f-bb1e-b55bdab5bb41
		summarizeBy: none
		sourceColumn: JMSIDLookupId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ParentIDLookupId
		dataType: string
		isHidden
		lineageTag: 73e50468-8401-4632-b417-54641df0432c
		summarizeBy: none
		sourceColumn: ParentIDLookupId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column JMSReadyTBCComments
		dataType: string
		isHidden
		lineageTag: f25c6ce1-c2ea-41c3-aa8e-b5496ba24950
		summarizeBy: none
		sourceColumn: JMSReadyTBCComments

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OData__ColorTag
		dataType: string
		isHidden
		lineageTag: a5a3e046-37c5-4bf6-a05f-1bdbefa583be
		summarizeBy: none
		sourceColumn: OData__ColorTag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column VControlTableAdded
		dataType: string
		isHidden
		lineageTag: 2a019ce8-36a2-4974-ba74-2256dbcdd875
		summarizeBy: none
		sourceColumn: VControlTableAdded

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Mgt. System'
		dataType: string
		isHidden
		lineageTag: 716d7ea2-7dc3-4625-88d5-f8599ac19586
		summarizeBy: none
		sourceColumn: Mgt. System

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ReviewPeriod
		dataType: string
		isHidden
		lineageTag: 4000f089-b392-40a9-8401-025feef57fa1
		summarizeBy: none
		sourceColumn: ReviewPeriod

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Process AuthorityId'
		dataType: string
		isHidden
		lineageTag: f1500ff3-aced-4de0-9239-817bffd61b1e
		summarizeBy: none
		sourceColumn: Process AuthorityId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Process AuthorityStringId'
		dataType: string
		isHidden
		lineageTag: 70eacc00-fee8-4931-9e50-9eb8db812e49
		summarizeBy: none
		sourceColumn: Process AuthorityStringId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OData__ip_UnifiedCompliancePolicyProperties
		dataType: string
		isHidden
		lineageTag: 09d072ec-6829-4015-827b-fa0bf150784b
		summarizeBy: none
		sourceColumn: OData__ip_UnifiedCompliancePolicyProperties

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BusinessAreaL1
		dataType: string
		isHidden
		lineageTag: bc30cc8c-e9cf-45e9-9807-a334eb0eb611
		summarizeBy: none
		sourceColumn: BusinessAreaL1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ContinualImprovementRequired
		dataType: string
		isHidden
		lineageTag: 8ced798b-5a9d-43a8-9628-3ece04bd6e54
		summarizeBy: none
		sourceColumn: ContinualImprovementRequired

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Document MS IDId'
		dataType: string
		isHidden
		lineageTag: e6acfff6-087e-438a-862a-1bd0b5d55384
		summarizeBy: none
		sourceColumn: Document MS IDId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'ID.1'
		dataType: string
		isHidden
		lineageTag: cb837483-80ec-4d58-b139-e9915717a835
		summarizeBy: none
		sourceColumn: ID.1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: string
		isHidden
		lineageTag: d201f1c9-9b2f-4cca-9e99-a7303a18fceb
		summarizeBy: none
		sourceColumn: Created

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AuthorId
		dataType: string
		isHidden
		lineageTag: c6afb17b-d34c-49f2-81d1-1d98af3ba4c2
		summarizeBy: none
		sourceColumn: AuthorId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Modified
		dataType: string
		isHidden
		lineageTag: 879e14e4-70dc-4190-bdb6-ff87db74a0a4
		summarizeBy: none
		sourceColumn: Modified

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EditorId
		dataType: string
		isHidden
		lineageTag: 3ddbc763-90f5-43c7-beae-ca777a9f9e39
		summarizeBy: none
		sourceColumn: EditorId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OData__CopySource
		dataType: string
		isHidden
		lineageTag: 2e62e8aa-501f-4dc5-96ca-73a982848490
		summarizeBy: none
		sourceColumn: OData__CopySource

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CheckoutUserId
		dataType: string
		isHidden
		lineageTag: 182c0046-22bf-4532-a57d-7c45c739c58d
		summarizeBy: none
		sourceColumn: CheckoutUserId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OData__UIVersionString
		dataType: string
		isHidden
		lineageTag: bde3bbbf-f5ed-4373-9cba-ae1dd76c5b28
		summarizeBy: none
		sourceColumn: OData__UIVersionString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column GUID
		dataType: string
		isHidden
		lineageTag: 74a618ac-3a50-444a-84b8-f95e391189e1
		summarizeBy: none
		sourceColumn: GUID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Content Type'
		dataType: string
		isHidden
		lineageTag: 8a0d95b1-dfa5-4f9d-acd0-59736cfa8262
		summarizeBy: none
		sourceColumn: Content Type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'JMS ID'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 74d956c8-e19e-46a5-945d-7434a61a2771
		summarizeBy: count
		sourceColumn: JMS ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'FieldValuesAsHtml.FileLeafRef.2.1'
		dataType: string
		isHidden
		lineageTag: cfc96df0-0645-4f51-94e7-e5154a4271ef
		summarizeBy: none
		sourceColumn: FieldValuesAsHtml.FileLeafRef.2.1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'FieldValuesAsHtml.FileLeafRef.2.2'
		dataType: string
		isHidden
		lineageTag: 06dffb41-009e-48e1-b13a-52ce14cca4a1
		summarizeBy: none
		sourceColumn: FieldValuesAsHtml.FileLeafRef.2.2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'FieldValuesAsHtml.Title'
		dataType: string
		isHidden
		lineageTag: 081c9af4-d76a-40d9-b2a2-37e2315b588b
		summarizeBy: none
		sourceColumn: FieldValuesAsHtml.Title

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'FieldValuesAsText.ReviewDate'
		dataType: string
		isHidden
		lineageTag: 8af0eb77-9de5-4db5-9077-44a08b87a861
		summarizeBy: none
		sourceColumn: FieldValuesAsText.ReviewDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Document Owner'
		dataType: string
		isHidden
		lineageTag: 14d430e1-0492-447e-b9fa-a7c8392cb203
		summarizeBy: none
		sourceColumn: Document Owner

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Process Authority'
		dataType: string
		isHidden
		lineageTag: a8b71259-39a0-4303-8f65-8b76b75f9400
		summarizeBy: none
		sourceColumn: Process Authority

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column '10K or 30K'
		dataType: string
		isHidden
		lineageTag: b7564f58-02b7-49c6-9e2d-e5048353330d
		summarizeBy: none
		sourceColumn: 10K or 30K

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Review Days'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 7f9facec-67c2-4e42-b737-ee2ba2271686
		summarizeBy: sum
		sourceColumn: Review Days

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Review Priority'
		dataType: string
		isHidden
		lineageTag: e6d3e907-1fec-4461-bc72-05445e1dba0d
		summarizeBy: none
		sourceColumn: Review Priority

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'JMS Table (2)' = m
		mode: import
		source = ```
				let
				    Source = SharePoint.Tables("https://kbsmaritime.sharepoint.com/sites/JointManagementSystem", [ApiVersion = 15]),
				    #"7a204d33-f1a5-4660-9105-822ef3cfee94" = Source{[Id="7a204d33-f1a5-4660-9105-822ef3cfee94"]}[Items],
				    #"Sorted Rows" = Table.Sort(#"7a204d33-f1a5-4660-9105-822ef3cfee94",{{"Title", Order.Ascending}}),
				    #"Expanded ContentType" = Table.ExpandRecordColumn(#"Sorted Rows", "ContentType", {"Name"}, {"ContentType.Name"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded ContentType",{{"ContentType.Name", "Content Type"}}),
				    #"Expanded FieldValuesAsHtml" = Table.ExpandRecordColumn(#"Renamed Columns", "FieldValuesAsHtml", {"FileLeafRef", "Title"}, {"FieldValuesAsHtml.FileLeafRef", "FieldValuesAsHtml.Title"}),
				    #"Expanded DocumentOwner" = Table.ExpandRecordColumn(#"Expanded FieldValuesAsHtml", "DocumentOwner", {"Title"}, {"DocumentOwner.Title"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded DocumentOwner",{{"DocumentOwner.Title", "Document Owner"}}),
				    #"Expanded Process Authority" = Table.ExpandRecordColumn(#"Renamed Columns1", "Process Authority", {"Title"}, {"Process Authority.Title"}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Expanded Process Authority",{{"Process Authority.Title", "Process Authority"}}),
				    #"Expanded FieldValuesAsText" = Table.ExpandRecordColumn(#"Renamed Columns2", "FieldValuesAsText", {"ReviewDate"}, {"FieldValuesAsText.ReviewDate"}),
				    #"Renamed Columns3" = Table.RenameColumns(#"Expanded FieldValuesAsText",{{"ServerRedirectedEmbedUri", "Document Link"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns3",{{"ReviewDate", type date}}),
				    #"Filtered to remove Null" = Table.SelectRows(#"Changed Type", each [ReviewDate] <> null),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Filtered to remove Null", "FieldValuesAsHtml.FileLeafRef", Splitter.SplitTextByEachDelimiter({"-"}, QuoteStyle.Csv, false), {"FieldValuesAsHtml.FileLeafRef.1", "FieldValuesAsHtml.FileLeafRef.2"}),
				    #"Renamed Columns4" = Table.RenameColumns(#"Split Column by Delimiter",{{"FieldValuesAsHtml.FileLeafRef.1", "JMS ID"}}),
				    #"Split Column by Delimiter1" = Table.SplitColumn(#"Renamed Columns4", "FieldValuesAsHtml.FileLeafRef.2", Splitter.SplitTextByEachDelimiter({"."}, QuoteStyle.Csv, true), {"FieldValuesAsHtml.FileLeafRef.2.1", "FieldValuesAsHtml.FileLeafRef.2.2"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"JMS ID", Int64.Type}, {"FieldValuesAsHtml.FileLeafRef.2.1", type text}, {"FieldValuesAsHtml.FileLeafRef.2.2", type text}}),
				    #"Renamed Columns5" = Table.RenameColumns(#"Changed Type1",{{"ID", "ID.1"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns5",{{"ReviewDate", type date}}),
				    #"10K/30K" = Table.AddColumn(#"Changed Type2", "10K or 30K", each if [JMS ID] >= 10000 and [JMS ID] <= 10999 then "10K"
				  else if [JMS ID] >= 15000 and [JMS ID] <= 15999 then "15K"
				  else if [JMS ID] >= 30000 then "30K" 
				  else null),
				    #"Days to Review" = Table.AddColumn(#"10K/30K", "Review Days", each Duration.Days([ReviewDate] - Date.From(DateTime.LocalNow()))),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Days to Review",{{"Review Days", Int64.Type}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type3", {"10K or 30K"}),
				    #"Sorted column/ Remove Error" = Table.Sort(#"Removed Errors",{{"Review Days", Order.Ascending}}),
				    #"Defining Review Priority" = Table.AddColumn(#"Sorted column/ Remove Error", "Review Priority", each if  [Review Days]<= 0 then "Overdue"
				  else if [Review Days] >= 1 and [Review Days] < 30 then "01-30 Days"
				  else if [Review Days] >= 30 and [Review Days] < 60 then "31-60 Days"
				  else if [Review Days] >= 60 and [Review Days]< 90 then "61-90 Days"
				  else if [Review Days] < 365 then " = 1Year"
				  else "> 1Year")
				in
				    #"Defining Review Priority"
				```

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

