/// JMS Table stores document details such as title, owner, review dates, compliance status, priority, and related comments, supporting document tracking and review management. This table is designed to support document management processes by capturing key metadata and review-related details for each document entry.
table 'JMS Table'
	lineageTag: 2ece3abf-5276-4fe5-9304-714b53fe15a6

	column Id
		dataType: string
		lineageTag: 594b9e45-fde6-4bf8-b11e-fb33ed48c6b3
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column 'Document Link'
		dataType: string
		lineageTag: e58b5141-cb5c-4382-95d5-ae72004df0c5
		summarizeBy: none
		sourceColumn: Document Link

		annotation SummarizationSetBy = Automatic

	column 'Quality Team Comments'
		dataType: string
		lineageTag: 5f596d64-505b-4595-98b5-735551ee0ab9
		summarizeBy: none
		sourceColumn: Quality Team Comments

		annotation SummarizationSetBy = Automatic

	column BusinessAreaL1
		dataType: string
		lineageTag: dd6a7e54-1b50-4279-9e17-800159f364b0
		summarizeBy: none
		sourceColumn: BusinessAreaL1

		annotation SummarizationSetBy = Automatic

	column ContinualImprovementRequired
		dataType: string
		lineageTag: 35a49ffd-bc7d-405f-abfc-bfa38f582d32
		summarizeBy: none
		sourceColumn: ContinualImprovementRequired

		annotation SummarizationSetBy = Automatic

	column Created
		dataType: dateTime
		formatString: Short Date
		lineageTag: fbe56672-99e2-43a4-8ac3-265e741d1d2a
		summarizeBy: none
		sourceColumn: Created

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Modified
		dataType: dateTime
		formatString: Short Date
		lineageTag: d52c8cd6-8bec-457a-87bd-afa0c6e92e1b
		summarizeBy: none
		sourceColumn: Modified

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column GUID
		dataType: string
		lineageTag: f6ab0a65-9c07-42d0-9838-2db193da3173
		summarizeBy: none
		sourceColumn: GUID

		annotation SummarizationSetBy = Automatic

	column 'Content Type'
		dataType: string
		lineageTag: 9f152cc2-5dc8-4388-9a35-155989b66b07
		summarizeBy: none
		sourceColumn: Content Type

		annotation SummarizationSetBy = Automatic

	column 'JMS ID'
		dataType: int64
		formatString: 0
		lineageTag: 8d19d8d9-caf5-4391-8291-be72f9bf3ae1
		summarizeBy: count
		sourceColumn: JMS ID

		annotation SummarizationSetBy = Automatic

	column ReviewDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: ea11de14-21a5-4fc9-a712-3e424cc70630
		summarizeBy: none
		sourceColumn: ReviewDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Document Owner'
		dataType: string
		lineageTag: dfab9064-04af-4ec8-a662-8b0b92356ba3
		summarizeBy: none
		sourceColumn: Document Owner

		annotation SummarizationSetBy = Automatic

	column 'Process Authority'
		dataType: string
		lineageTag: e678a2b6-822f-46cc-a316-88de316eb402
		summarizeBy: none
		sourceColumn: Process Authority

		annotation SummarizationSetBy = Automatic

	column 'Review Days'
		dataType: string
		lineageTag: 47316d09-130c-4ff1-b76d-ecb5c3a190af
		summarizeBy: none
		sourceColumn: Review Days

		annotation SummarizationSetBy = Automatic

	column 'Review Status'
		dataType: string
		lineageTag: 46aeceae-bacf-49cb-bbc3-33226d66ce5f
		summarizeBy: none
		sourceColumn: Review Status

		annotation SummarizationSetBy = Automatic

	column 'Compliant and Expired'
		dataType: string
		lineageTag: 4cfe6462-4f51-4eeb-8856-922bd2251a5f
		summarizeBy: none
		sourceColumn: Compliant and Expired

		annotation SummarizationSetBy = Automatic

	column 'Expired and Compliant - Values'
		dataType: int64
		formatString: 0
		lineageTag: ffc1692a-8f1c-4884-9fb6-812df07e1df4
		summarizeBy: sum
		sourceColumn: Expired and Compliant - Values

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'Owner Email'
		dataType: string
		lineageTag: 58b7dc9a-7074-4456-bfd4-e2565cf653cb
		summarizeBy: none
		sourceColumn: Owner Email

		annotation SummarizationSetBy = Automatic

	column 'Title.'
		dataType: string
		lineageTag: 1eb33fe3-e449-4cfa-90a7-fc9b2e2599ce
		summarizeBy: none
		sourceColumn: Title.

		annotation SummarizationSetBy = Automatic

	column 'Review Status Sort'
		dataType: string
		lineageTag: f86cf079-9527-4480-8b73-48bf2ecd1d30
		summarizeBy: none
		sourceColumn: Review Status Sort

		annotation SummarizationSetBy = Automatic

	partition 'JMS Table' = m
		mode: import
		source =
				let
				    Source = SharePoint.Tables("https://kbsmaritime.sharepoint.com/sites/JointManagementSystem", [ApiVersion = 15]),
				    #"7a204d33-f1a5-4660-9105-822ef3cfee94" = Source{[Id="7a204d33-f1a5-4660-9105-822ef3cfee94"]}[Items],
				    #"Removed Other Columns" = Table.SelectColumns(#"7a204d33-f1a5-4660-9105-822ef3cfee94",{"Id", "ServerRedirectedEmbedUrl", "ReviewDate", "JMSReadyTBCComments", "BusinessAreaL1", "ContinualImprovementRequired", "Created", "Modified", "GUID", "ContentType", "FieldValuesAsHtml", "FieldValuesAsText", "DocumentOwner", "Process Authority"}),
				    #"Expanded ContentType" = Table.ExpandRecordColumn(#"Removed Other Columns", "ContentType", {"Name"}, {"ContentType.Name"}),
				    #"Removed the Prefix (JMS)" = Table.ReplaceValue(#"Expanded ContentType","JMS","",Replacer.ReplaceText,{"ContentType.Name"}),
				    #"Renamed Col. to Content Type" = Table.RenameColumns(#"Removed the Prefix (JMS)",{{"ContentType.Name", "Content Type"}}),
				    #"Expanded FieldValuesAsHtml" = Table.ExpandRecordColumn(#"Renamed Col. to Content Type", "FieldValuesAsHtml", {"FileLeafRef", "Title"}, {"FieldValuesAsHtml.FileLeafRef", "FieldValuesAsHtml.Title"}),
				    #"Expanded DocumentOwner" = Table.ExpandRecordColumn(#"Expanded FieldValuesAsHtml", "DocumentOwner", {"Title"}, {"DocumentOwner.Title"}),
				    #"Renamed Column to Doc. Owner" = Table.RenameColumns(#"Expanded DocumentOwner",{{"DocumentOwner.Title", "Document Owner"}}),
				    #"Expand to extract Process Authority" = Table.ExpandRecordColumn(#"Renamed Column to Doc. Owner", "Process Authority", {"Title"}, {"Process Authority.Title"}),
				    #"Renamed to Process Authority" = Table.RenameColumns(#"Expand to extract Process Authority",{{"Process Authority.Title", "Process Authority"}}),
				    #"Expanded to Extract Review Date" = Table.ExpandRecordColumn(#"Renamed to Process Authority", "FieldValuesAsText", {"ReviewDate"}, {"FieldValuesAsText.ReviewDate"}),
				    #"Renamed Column" = Table.RenameColumns(#"Expanded to Extract Review Date",{{"ServerRedirectedEmbedUrl", "Document Link"}}),
				    #"Changed to DateType" = Table.TransformColumnTypes(#"Renamed Column",{{"ReviewDate", type date}}),
				    #"Filtered out nulls" = Table.SelectRows(#"Changed to DateType", each ([ReviewDate] <> null)),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Filtered out nulls", "FieldValuesAsHtml.FileLeafRef", Splitter.SplitTextByEachDelimiter({"-"}, QuoteStyle.Csv, false), {"FieldValuesAsHtml.FileLeafRef.1", "FieldValuesAsHtml.FileLeafRef.2"}),
				    #"Renamed Col. to JMS ID" = Table.RenameColumns(#"Split Column by Delimiter",{{"FieldValuesAsHtml.FileLeafRef.1", "JMS ID"}}),
				    #"Split Column" = Table.SplitColumn(#"Renamed Col. to JMS ID", "FieldValuesAsHtml.FileLeafRef.2", Splitter.SplitTextByEachDelimiter({"."}, QuoteStyle.Csv, true), {"FieldValuesAsHtml.FileLeafRef.2.1", "FieldValuesAsHtml.FileLeafRef.2.2"}),
				    #"Changed Data Type" = Table.TransformColumnTypes(#"Split Column",{{"JMS ID", Int64.Type}, {"FieldValuesAsHtml.FileLeafRef.2.1", type text}, {"FieldValuesAsHtml.FileLeafRef.2.2", type text}}),
				    #"Removed Suffix" = Table.ReplaceValue(#"Changed Data Type","(KBS PC)","",Replacer.ReplaceText,{"Document Owner"}),
				    #"Days to Review" = Table.AddColumn(#"Removed Suffix", "Review Days", each Duration.Days([ReviewDate] - Date.From(DateTime.LocalNow()))),
				    #"Defined Review Status" = Table.AddColumn(#"Days to Review", "Review Status", each if  [Review Days]<= 0 then "Overdue"
				  else if [Review Days] >= 1 and [Review Days] < 30 then "01-30 Days"
				  else if [Review Days] >= 30 and [Review Days] < 60 then "31-60 Days"
				  else if [Review Days] >= 60 then "61+ Days"
				  else ""),
				    #"Removed empty Date" = Table.SelectRows(#"Defined Review Status", each ([Review Status] <> "")),
				    #"Filtered Rows" = Table.SelectRows(#"Removed empty Date", each true),
				    #"Compliant and Expired Status (Defined)" = Table.AddColumn(#"Filtered Rows", "Compliant and Expired", each if [Review Status] = "Overdue" then "Overdue" else "Complaint"),
				    #"Expired and Compliant - Outcome 1 or 2" = Table.AddColumn(#"Compliant and Expired Status (Defined)", "Expired and Compliant - Values", each if [Compliant and Expired] = "Overdue" then 1 else 2),
				    #"Reordered Columns" = Table.ReorderColumns(#"Expired and Compliant - Outcome 1 or 2",{"Id", "Document Link", "JMSReadyTBCComments", "BusinessAreaL1", "ContinualImprovementRequired", "Created", "Modified", "GUID", "Content Type", "JMS ID", "FieldValuesAsHtml.FileLeafRef.2.1", "FieldValuesAsHtml.FileLeafRef.2.2", "FieldValuesAsHtml.Title", "ReviewDate", "FieldValuesAsText.ReviewDate", "Document Owner", "Process Authority"}),
				    #"Replaced 'Null' with Nothing" = Table.ReplaceValue(#"Reordered Columns",null,"",Replacer.ReplaceValue,{"JMSReadyTBCComments"}),
				    #"Renamed to Quality Team Comments" = Table.RenameColumns(#"Replaced 'Null' with Nothing",{{"JMSReadyTBCComments", "Quality Team Comments"}}),
				    #"Added Owner Email Address" = Table.AddColumn(#"Renamed to Quality Team Comments", "Owner Email", each Text.Lower(Text.Replace([Document Owner], " ", ".")) & "@kbsMaritime.com"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Owner Email Address",{{"ContinualImprovementRequired", type text}}),
				    #"Replaced true with Yes" = Table.ReplaceValue(#"Changed Type","true","Yes",Replacer.ReplaceText,{"ContinualImprovementRequired"}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Replaced true with Yes", "FieldValuesAsHtml.FileLeafRef.2.1", "FieldValuesAsHtml.FileLeafRef.2.1 - Copy"),
				    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"FieldValuesAsHtml.FileLeafRef.2.1 - Copy", "Title."}}),
				    #"Removed Suffix (KBS PC)" = Table.ReplaceValue(#"Renamed Columns","(KBS PC)","",Replacer.ReplaceText,{"Process Authority"}),
				    #"Replaced Errors with JMS ID ""10649""" = Table.ReplaceErrorValues(#"Removed Suffix (KBS PC)", {{"JMS ID", 10649}}),
				    #"Change ""Null"" to Doc. Title" = Table.ReplaceValue(#"Replaced Errors with JMS ID ""10649""",null,"ATEX Equipment Request Form",Replacer.ReplaceValue,{"Title."}),
				    #"Added Conditional Column for sorting" = Table.AddColumn(#"Change ""Null"" to Doc. Title", "Review Status Sort", each if [Review Status] = "Overdue" then 1 else if [Review Status] = "01-30 Days" then 2 else if [Review Status] = "31-60 Days" then 3 else if [Review Status] = "61+ Days" then 4 else 5),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Conditional Column for sorting",{"FieldValuesAsText.ReviewDate", "FieldValuesAsHtml.FileLeafRef.2.2", "FieldValuesAsHtml.FileLeafRef.2.1", "FieldValuesAsHtml.Title"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

