/// Sorted Rows table contains columns for Review Status and Priority, which help organize and classify review items by their status and priority level.
table 'Sorted Rows'
	isHidden
	lineageTag: 6852a746-ccb3-4537-bdf4-9e6e482f1c21

	column 'Review Status'
		dataType: string
		isHidden
		lineageTag: d183f75e-3a07-47b5-84f2-d38aa7c67bdd
		summarizeBy: none
		sourceColumn: Review Status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Priority
		dataType: string
		isHidden
		lineageTag: 8639d212-d034-48ca-a0ef-fe3759d149ea
		summarizeBy: none
		sourceColumn: Priority

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Sorted Rows' = m
		mode: import
		source =
				let
				    #"Updated JMS Table" = let
				    Source = SharePoint.Tables("https://kbsmaritime.sharepoint.com/sites/JointManagementSystem", [ApiVersion = 15]),
				    #"7a204d33-f1a5-4660-9105-822ef3cfee94" = Source{[Id="7a204d33-f1a5-4660-9105-822ef3cfee94"]}[Items],
				    #"Renamed Columns" = Table.RenameColumns(#"7a204d33-f1a5-4660-9105-822ef3cfee94",{{"ID", "ID.1"}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns",{"CheckoutUser"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"ServerRedirectedEmbedUri", "Document Link"}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns1",{"ServerRedirectedEmbedUrl", "ContentTypeId", "FileSystemObjectType", "ComplianceAssetId"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Columns1", each ([Title] <> null)),
				    #"Removed Columns2" = Table.RemoveColumns(#"Filtered Rows",{"DocumentOwnerId", "DocumentOwnerStringId", "MethodStatementServiceDeliveryPlan", "OData__Copyright"}),
				    #"Extracted Date" = Table.TransformColumns(#"Removed Columns2",{{"ReviewDate", DateTime.Date, type date}}),
				    #"Removed Columns3" = Table.RemoveColumns(#"Extracted Date",{"URL", "External Ref. Type", "Mgt. Plan Type", "Standard Type", "Strategy Type", "OData__ColorTag", "VControlTableAdded"}),
				    #"Removed Columns4" = Table.RemoveColumns(#"Removed Columns3",{"Mgt. System", "Process AuthorityId", "Process AuthorityStringId", "AuthorId", "OData__CopySource", "CheckoutUserId", "OData__UIVersionString", "GUID", "FirstUniqueAncestorSecurableObject", "RoleAssignments", "AttachmentFiles"}),
				    #"Expanded ContentType" = Table.ExpandRecordColumn(#"Removed Columns4", "ContentType", {"Name"}, {"ContentType.Name"}),
				    #"Renamed Columns3" = Table.RenameColumns(#"Expanded ContentType",{{"ContentType.Name", "Content Type"}}),
				    #"Removed Columns5" = Table.RemoveColumns(#"Renamed Columns3",{"GetDlpPolicyTip"}),
				    #"Expanded FieldValuesAsHtml" = Table.ExpandRecordColumn(#"Removed Columns5", "FieldValuesAsHtml", {"FileLeafRef", "Title"}, {"FieldValuesAsHtml.FileLeafRef", "FieldValuesAsHtml.Title"}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Expanded FieldValuesAsHtml", "FieldValuesAsHtml.FileLeafRef", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"FieldValuesAsHtml.FileLeafRef.1", "FieldValuesAsHtml.FileLeafRef.2", "FieldValuesAsHtml.FileLeafRef.3", "FieldValuesAsHtml.FileLeafRef.4"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"FieldValuesAsHtml.FileLeafRef.1", Int64.Type}, {"FieldValuesAsHtml.FileLeafRef.2", type text}, {"FieldValuesAsHtml.FileLeafRef.3", type text}, {"FieldValuesAsHtml.FileLeafRef.4", type text}}),
				    #"Renamed Columns4" = Table.RenameColumns(#"Changed Type",{{"FieldValuesAsHtml.FileLeafRef.1", "JMS ID"}}),
				    #"Removed Columns6" = Table.RemoveColumns(#"Renamed Columns4",{"FieldValuesAsHtml.FileLeafRef.2", "FieldValuesAsHtml.FileLeafRef.3", "FieldValuesAsHtml.FileLeafRef.4"}),
				    #"Renamed Columns5" = Table.RenameColumns(#"Removed Columns6",{{"FieldValuesAsHtml.Title", "Document Title"}}),
				    #"Expanded Process Authority" = Table.ExpandRecordColumn(#"Renamed Columns5", "Process Authority", {"Title"}, {"Process Authority.Title"}),
				    #"Renamed Columns6" = Table.RenameColumns(#"Expanded Process Authority",{{"Process Authority.Title", "Process Authority"}}),
				    #"Removed Columns7" = Table.RemoveColumns(#"Renamed Columns6",{"ParentIDLookup", "ID.1", "EditorId"}),
				    #"Removed Columns8" = Table.RemoveColumns(#"Removed Columns7",{"Author", "Editor", "JMSIDLookup", "SharedWithUsers", "TaxCatchAll", "Additional Authorisers"}),
				    #"Expanded DocumentOwner" = Table.ExpandRecordColumn(#"Removed Columns8", "DocumentOwner", {"Title"}, {"DocumentOwner.Title"}),
				    #"Renamed Columns7" = Table.RenameColumns(#"Expanded DocumentOwner",{{"DocumentOwner.Title", "Document Owner"}}),
				    #"Removed Columns9" = Table.RemoveColumns(#"Renamed Columns7",{"Additional AuthorisersId", "Additional AuthorisersStringId", "Eng. Auth. Req'd?", "SHE Auth. Req'd?", "SharedWithUsersId", "SharedWithDetails", "IM Auth. Req'd?", "JMSIDLookupId", "ParentIDLookupId"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Removed Columns9", each true),
				    #"Removed Columns10" = Table.RemoveColumns(#"Filtered Rows1",{"Created", "Modified"}),
				    #"Expanded FieldValuesAsText" = Table.ExpandRecordColumn(#"Removed Columns10", "FieldValuesAsText", {"ProcessID_x003A_Procedure"}, {"FieldValuesAsText.ProcessID_x003A_Procedure"}),
				    #"Renamed Columns8" = Table.RenameColumns(#"Expanded FieldValuesAsText",{{"FieldValuesAsText.ProcessID_x003A_Procedure", "Parent Documrnt Filter"}}),
				    #"Removed Columns11" = Table.RemoveColumns(#"Renamed Columns8",{"JMSReadyTBCComments", "ReviewPeriod", "FieldValuesForEdit", "File", "Folder", "LikedByInformation", "ParentList", "Properties", "Versions"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns11", "Days till Review", each DateTime.From([ReviewDate]) - DateTime.LocalNow()),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom",{{"Days till Review", Int64.Type}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Changed Type4",{{"ReviewDate", type datetime}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Changed Type3",{{"Days till Review", type duration}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type2",{{"ReviewDate", type date}, {"Days till Review", Int64.Type}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type1", "Status", each if [Days till Review] < 0 then "Expired"
				  else if [Days till Review] >= 0 and [Days till Review] < 30 then "Expires within 30 Days"
				  else if [Days till Review] >= 30 and [Days till Review] < 60 then "Expires within 60 Days"
				  else if [Days till Review] >= 60 and [Days till Review] < 180 then "Expires within 180 Days"
				  else "Expires within 180+ Days"),
				    #"Renamed Columns9" = Table.RenameColumns(#"Added Custom1",{{"Status", "Review Status"}}),
				    #"Added Custom2" = Table.AddColumn(#"Renamed Columns9", "Custom", each if [Days till Review] < 0 then "Review Overdue"
				  else if [Days till Review] >= 0 and [Days till Review] < 30 then "Review within 30 Days"
				  else if [Days till Review] >= 30 and [Days till Review] < 60 then "Review within 60 Days"
				  else if [Days till Review] >= 60 and [Days till Review] < 90 then "Review within 90 Days"
				  else if [Days till Review] < 365 then "Review within 1 year"
				  else "Greater than 1 year"),
				    #"Renamed Columns10" = Table.RenameColumns(#"Added Custom2",{{"Custom", "Review Priorty"}}),
				    #"Added Custom3" = Table.AddColumn(#"Renamed Columns10", "Custom", each if [JMS ID] >= 10000 and [JMS ID] <= 10999 then "10K"
				  else if [JMS ID] >= 15000 and [JMS ID] <= 15999 then "15K"
				  else if [JMS ID] >= 30000 then "30K"
				  else null),
				    #"Renamed Columns11" = Table.RenameColumns(#"Added Custom3",{{"Custom", "10k or 30K"}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Renamed Columns11", "Review Status", "Review Status - Copy")
				in
				    #"Renamed Columns11",
				    #"Filtered Rows" = Table.SelectRows(#"Updated JMS Table", each ([ReviewDate] <> null)),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Filtered Rows", "Review Status", "Review Status - Copy"),
				    #"Replaced Value" = Table.ReplaceValue(#"Duplicated Column","Expires within 180+ Days","Compliant",Replacer.ReplaceText,{"Review Status - Copy"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Expires within 60 Days","Compliant",Replacer.ReplaceText,{"Review Status - Copy"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Expires within 180 Days","Compliant",Replacer.ReplaceText,{"Review Status - Copy"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Expires within 30 Days","Compliant",Replacer.ReplaceText,{"Review Status - Copy"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value3",{{"Review Status - Copy", "Compliant and Expired"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Compliant and Expired", type text}}),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Changed Type", "Compliant and Expired", "Compliant and Expired - Copy"),
				    #"Replaced Value4" = Table.ReplaceValue(#"Duplicated Column1","Compliant","2",Replacer.ReplaceText,{"Compliant and Expired - Copy"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Expired","1",Replacer.ReplaceText,{"Compliant and Expired - Copy"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value5",{{"Compliant and Expired - Copy", Int64.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type1",{"Review Status"}),
				    #"Duplicated Column2" = Table.DuplicateColumn(#"Removed Other Columns", "Review Status", "Review Status - Copy"),
				    #"Replaced Value6" = Table.ReplaceValue(#"Duplicated Column2","Expires within 180+ Days","1",Replacer.ReplaceText,{"Review Status - Copy"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","Expired","5",Replacer.ReplaceText,{"Review Status - Copy"}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","Expires within 180 Days","2",Replacer.ReplaceText,{"Review Status - Copy"}),
				    #"Replaced Value9" = Table.ReplaceValue(#"Replaced Value8","Expires within 60 Days","3",Replacer.ReplaceText,{"Review Status - Copy"}),
				    #"Replaced Value10" = Table.ReplaceValue(#"Replaced Value9","Expires within 30 Days","4",Replacer.ReplaceText,{"Review Status - Copy"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Replaced Value10",{{"Review Status - Copy", "Priority"}}),
				    #"Removed Duplicates" = Table.Distinct(#"Renamed Columns1", {"Review Status"})
				in
				    #"Removed Duplicates"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

