DEFINE
	VAR __DS0FilterTable = 
		FILTER(
			KEEPFILTERS(VALUES('JMS Table'[Document Owner])),
			NOT(ISBLANK('JMS Table'[Document Owner]))
		)

	VAR __DS0FilterTable2 = 
		FILTER(
			KEEPFILTERS(VALUES('DateTable'[Date])),
			NOT('DateTable'[Date] IN {BLANK()})
		)

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			'JMS Table'[JMS ID],
			'JMS Table'[Title],
			'JMS Table'[Content Type],
			'JMS Table'[Document Owner],
			'JMS Table'[Days till Review],
			'JMS Table'[Review Date],
			'JMS Table'[Quality Team Comments],
			'JMS Table'[Review Priority Signs],
			'JMS Table'[Review Status Signs],
			'JMS Table'[Owners Email],
			__DS0FilterTable,
			__DS0FilterTable2,
			"Email_Link", 'JMS Table'[Email Link],
			"SumDays_till_Review", IGNORE(CALCULATE(SUM('JMS Table'[Days till Review]))),
			"MinDocument_Link", IGNORE(CALCULATE(MIN('JMS Table'[Document Link])))
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(
			501,
			__DS0Core,
			'JMS Table'[Review Priority Signs],
			1,
			'JMS Table'[JMS ID],
			1,
			'JMS Table'[Title],
			1,
			'JMS Table'[Content Type],
			1,
			'JMS Table'[Document Owner],
			1,
			'JMS Table'[Days till Review],
			1,
			'JMS Table'[Review Date],
			1,
			'JMS Table'[Quality Team Comments],
			1,
			'JMS Table'[Review Status Signs],
			1,
			'JMS Table'[Owners Email],
			1
		)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	'JMS Table'[Review Priority Signs],
	'JMS Table'[JMS ID],
	'JMS Table'[Title],
	'JMS Table'[Content Type],
	'JMS Table'[Document Owner],
	'JMS Table'[Days till Review],
	'JMS Table'[Review Date],
	'JMS Table'[Quality Team Comments],
	'JMS Table'[Review Status Signs],
	'JMS Table'[Owners Email]